---
- name: Deploy image
  hosts: "dev"
  become: true
  ignore_errors: yes
  gather_facts: false

  pre_tasks:

   - name: pull an image 13.58.189.222:8082/kdevops
     shell: "docker login -u admin -p kalyan 13.58.189.222:8082/repository/kdevops/ && docker pull 13.58.189.222:8082/kdevops"
     register: deployStatus
   - shell: "docker rm -f spacegame"
   - shell: "docker run -d --name spacegame -p 8081:80  13.58.189.222:8082/kdevops"
