version: 2
jobs:
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo
          command: |
            apt-get -y -qq update
            apt-get install -y python-pip python-dev build-essential
            pip install  --upgrade setuptools
            pip install  awsebcli --upgrade

      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet restore 
      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet build 
      - run:
          name: dotnet publish
          working_directory: ~/repo
          command: |
            dotnet publish -c debug -o  ~/repo/artifact
      - store_artifacts:
          path: ~/repo/artifact
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile kenani]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use circleci-beanstalk-example --profile kenani --region us-east-1
            eb init --region us-east-1 --platform Docker circleci-beanstalk-example        
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
