version: 2
jobs:
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo
          command: |
            apt-get -y -qq update
            apt-get install -y python-pip python-dev build-essential
            pip install  --upgrade setuptools
            pip install  awsebcli --upgrade

      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet restore 
      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet build 
      - run:
          name: dotnet publish
          working_directory: ~/repo
          command: |
            dotnet publish -c debug -o  ~/repo/artifact
      - store_artifacts:
          path: ~/repo/artifact
      - run:
          name: eb try 
          working_directory: ~/repo/artifact
          command: |
            pwd
            eb init         
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
