version: 2
jobs:
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get install -y python-pip python-dev build-essential
            pip install  --upgrade setuptools
            pip install  awsebcli --upgrade

      - run:
          name: dotnet restore
          working_directory: /
          command: |
            dotnet restore
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
