version: 2
jobs:
  deploy:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: ~/repo
          command: |
            apt-get -y -qq update
            apt-get install -y python-pip python-dev build-essential
            pip install  --upgrade setuptools
            pip install  awsebcli --upgrade

      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet restore 
      - run:
          name: dotnet restore
          working_directory: ~/repo
          command: |
            dotnet build 
      - run:
          name: dotnet publish
          working_directory: ~/repo
          command: |
            dotnet publish -c debug -o  ~/repo/artifact
      - store_artifacts:
          path: ~/repo/artifact
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/repo/artifact/.aws
            touch ~/repo/artifact/.aws/config
            chmod 600 ~/repo/artifact/.aws/config
            echo "[profile kenani]" > ~/repo/artifact/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/repo/artifact/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/repo/artifact/.aws/config
      - run:
          name: Deploy to EB if branch is Master
          working_directory: ~/repo/artifact
          command: |
            eb init --region us-east-1 --platform iis-10.0 circleci-beanstalk-example 
            eb create circleci-beanstalk-example-test1
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
